# Generated by Django 4.2.1 on 2023-08-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.TextField(max_length=250)),
                ('photo', models.ImageField(upload_to='pics')),
                ('exp', models.TextField()),
            ],
        ),
    ]
